4 test Workflow

diff --git a/.github/workflows/Tabs_Test.yaml b/.github/workflows/Tabs_Test.yaml
--- a/.github/workflows/Tabs_Test.yaml
+++ b/.github/workflows/Tabs_Test.yaml
@@ -1,27 +1,36 @@
-name: Get modified tabs
+name: Gets all changed files, find tabs, generate report
 
 on: [pull_request]
 
 jobs:
   find-changed-files:
     runs-on: ubuntu-latest
-    name: modified-data
+    outputs:
+      files: ${{ steps.files.outputs.all }}  
     steps:
-      - uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
-
       - name: Get changed files
-        id: changed-files
-        uses: tj-actions/changed-files@v19
-
-      - name: Show all changed files
+        uses: jitterbit/get-changed-files@v1
+        id: files
+        with:
+          format: 'json'
+          token: ${{ secrets.GITHUB_TOKEN }}  
+      - run: | 
+              echo "List of changed files got succesfully"
+              echo "${{ steps.files.outputs.all }}"
+  find-tabs:
+    needs: find-changed-files
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        changed-files: ${{fromJson(needs.find-changed-files.outputs.files)}}
+      fail-fast: false
+    steps:
+      - uses: actions/checkout@v2.1.0
+      - name: Find tabs
         run: |
-          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
-            echo "$Files was changed" >> mod_files.log 2>&1
-            echo "Count Tab in files: `grep -P '\t' $file | wc -l`" >> mod_files.log 2>&1
-          done
-      - name: Report
+              echo "${{matrix.changed-files}}"
+              cat ${{matrix.changed-files}} | grep -P "\t" > ${{matrix.changed-files}}.log 2>&1 || echo "Tabs not found"
+      - name: Upload report
         uses: actions/upload-artifact@v2
         with:
-          path: mod_files.log
+          path: ${{ matrix.changed-files }}.log
